
package com.ttdev.cs;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.5
 * Mon Dec 28 12:56:07 HKT 2009
 * Generated source version: 2.2.5
 * 
 */
 
public class ComputeService_P1_Server{

    protected ComputeService_P1_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ComputeServiceImpl();
        String address = "http://localhost:8080/cs/p1";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ComputeService_P1_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
} 
