
/*
 * 
 */

package com.ttdev.cs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.5
 * Mon Dec 28 12:56:07 HKT 2009
 * Generated source version: 2.2.5
 * 
 */


@WebServiceClient(name = "ComputeService", 
                  wsdlLocation = "file:src/main/resources/ComputeService.wsdl",
                  targetNamespace = "http://ttdev.com/cs") 
public class ComputeService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ttdev.com/cs", "ComputeService");
    public final static QName P1 = new QName("http://ttdev.com/cs", "p1");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/ComputeService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:src/main/resources/ComputeService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url; 
    }

    public ComputeService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ComputeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComputeService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ComputeService
     */
    @WebEndpoint(name = "p1")
    public ComputeService getP1() {
        return super.getPort(P1, ComputeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComputeService
     */
    @WebEndpoint(name = "p1")
    public ComputeService getP1(WebServiceFeature... features) {
        return super.getPort(P1, ComputeService.class, features);
    }

}
