package com.ttdev.cs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.5
 * Mon Dec 28 12:56:07 HKT 2009
 * Generated source version: 2.2.5
 * 
 */
 
@WebService(targetNamespace = "http://ttdev.com/cs", name = "ComputeService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ComputeService {

    @WebResult(name = "computeResponse", targetNamespace = "http://ttdev.com/cs", partName = "parameters")
    @WebMethod(action = "http://ttdev.com/cs/compute")
    public java.lang.String compute(
        @WebParam(partName = "parameters", name = "compute", targetNamespace = "http://ttdev.com/cs")
        java.lang.String parameters
    );
}
 